
name: Deploy to EC2
on:
  push:
    branches:
      - main  # Change this if your default branch is different
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@3.141.19.165 << 'EOF'
            cd /home/ubuntu/app  # Change to your project directory
            git pull origin main
            sudo systemctl restart nginx
            sudo systemctl restart php8.1-fpm
            exit
          EOF
